In [ ]:
from langchain.document_loaders import TextLoader
from langchain_community.document_loaders import CSVLoader

In [6]:
loader = TextLoader("nvda_news_1.txt")

In [7]:
data = loader.load()

In [9]:
data[0].page_content

"The stock of NVIDIA Corp (NASDAQ:NVDA) experienced a daily loss of -3.56% and a 3-month gain of 32.35%. With an Earnings Per Share (EPS) (EPS) of $1.92, the question arises: is the stock significantly overvalued? This article aims to provide a detailed valuation analysis of NVIDIA, offering insights into its financial strength, profitability, growth, and more. We invite you to delve into this comprehensive analysis.\n\nCompany Overview\nWarning! GuruFocus has detected 10 Warning Signs with NVDA. Click here to check it out.\n\nNVDA 30-Year Financial Data\n\nThe intrinsic value of NVDA\n\n\nNVIDIA Corp (NASDAQ:NVDA) is a leading designer of discrete graphics processing units that enhance the experience on computing platforms. The firm's chips are widely used in various end markets, including PC gaming and data centers. In recent years, NVIDIA has broadened its focus from traditional PC graphics applications such as gaming to more complex and favorable opportunities, including artificial intelligence and autonomous driving, leveraging the high-performance capabilities of its products.\n\nCurrently, NVIDIA's stock price stands at $418.01, significantly higher than the GF Value of $310.28, indicating the stock might be overvalued. With a market cap of $1 trillion, the valuation seems steep. The following analysis aims to delve deeper into the company's value.\n\nIs NVIDIA's Stock Significantly Overvalued? A Comprehensive Valuation Analysis\nIs NVIDIA's Stock Significantly Overvalued? A Comprehensive Valuation Analysis\nUnderstanding the GF Value\nThe GF Value is a unique measure of the intrinsic value of a stock, calculated based on historical trading multiples, a GuruFocus adjustment factor, and future business performance estimates. If the stock price is significantly above the GF Value Line, it is overvalued, and its future return is likely to be poor. Conversely, if it is significantly below the GF Value Line, its future return will likely be higher.\n\nAccording to GuruFocus Value calculation, NVIDIA (NASDAQ:NVDA) appears to be significantly overvalued. The stock's current price of $418.01 per share and the market cap of $1 trillion further strengthen this assumption.\n\nGiven that NVIDIA is significantly overvalued, the long-term return of its stock is likely to be much lower than its future business growth.\n\nIs NVIDIA's Stock Significantly Overvalued? A Comprehensive Valuation Analysis\nIs NVIDIA's Stock Significantly Overvalued? A Comprehensive Valuation Analysis\nLink: These companies may deliver higher future returns at reduced risk.\n\nFinancial Strength of NVIDIA\nExamining the financial strength of a company is crucial before investing in its stock. Companies with poor financial strength pose a higher risk of permanent loss. NVIDIA's cash-to-debt ratio of 1.27 is worse than 58.04% of companies in the Semiconductors industry. However, NVIDIA's overall financial strength is 8 out of 10, indicating a strong financial position.\n\nIs NVIDIA's Stock Significantly Overvalued? A Comprehensive Valuation Analysis\nIs NVIDIA's Stock Significantly Overvalued? A Comprehensive Valuation Analysis\nProfitability and Growth\nConsistent profitability over the long term reduces the risk for investors. NVIDIA, with its profitability ranking of 10 out of 10, has been profitable for the past 10 years. The company's operating margin of 17.37% ranks better than 76.5% of companies in the Semiconductors industry.\n\nHowever, growth is a crucial factor in a company's valuation. NVIDIA's growth ranks worse than 52.99% of companies in the Semiconductors industry, with its 3-year average revenue growth rate better than 87.88% of companies in the industry.\n\nROIC vs WACC\nComparing a company's return on invested capital (ROIC) to its weighted average cost of capital (WACC) is an effective way to evaluate its profitability. Over the past 12 months, NVIDIA's ROIC was 20.32 while its WACC was 16.74, suggesting that the company is creating value for its shareholders.\n\nIs NVIDIA's Stock Significantly Overvalued? A Comprehensive Valuation Analysis\nIs NVIDIA's Stock Significantly Overvalued? A Comprehensive Valuation Analysis\nConclusion\nIn conclusion, NVIDIA (NASDAQ:NVDA) appears to be significantly overvalued. Despite its strong financial condition and profitability, its growth ranks lower than 52.99% of companies in the Semiconductors industry. To learn more about NVIDIA stock, you can check out its 30-Year Financials here.\n\nTo find out the high quality companies that may deliver above-average returns, please check out GuruFocus High Quality Low Capex Screener.\n\nThis article first appeared on GuruFocus."

In [12]:
from langchain.document_loaders import CSVLoader
loader = CSVLoader("Titanic-Dataset.csv")
data = loader.load()
len(data)

891

In [13]:
data

[Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 0}, page_content='PassengerId: 1\nSurvived: 0\nPclass: 3\nName: Braund, Mr. Owen Harris\nSex: male\nAge: 22\nSibSp: 1\nParch: 0\nTicket: A/5 21171\nFare: 7.25\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 1}, page_content='PassengerId: 2\nSurvived: 1\nPclass: 1\nName: Cumings, Mrs. John Bradley (Florence Briggs Thayer)\nSex: female\nAge: 38\nSibSp: 1\nParch: 0\nTicket: PC 17599\nFare: 71.2833\nCabin: C85\nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 2}, page_content='PassengerId: 3\nSurvived: 1\nPclass: 3\nName: Heikkinen, Miss. Laina\nSex: female\nAge: 26\nSibSp: 0\nParch: 0\nTicket: STON/O2. 3101282\nFare: 7.925\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 3}, page_content='PassengerId: 4\nSurvived: 1\nPclass: 1\nName: Futrelle, Mrs. Jacques Heath (Lily May Peel)\nSex: female\nAge: 35\nSibSp: 1\nParch: 0\nTicket: 113803\nFare: 53.1\nCabin: C123\nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 4}, page_content='PassengerId: 5\nSurvived: 0\nPclass: 3\nName: Allen, Mr. William Henry\nSex: male\nAge: 35\nSibSp: 0\nParch: 0\nTicket: 373450\nFare: 8.05\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 5}, page_content='PassengerId: 6\nSurvived: 0\nPclass: 3\nName: Moran, Mr. James\nSex: male\nAge: \nSibSp: 0\nParch: 0\nTicket: 330877\nFare: 8.4583\nCabin: \nEmbarked: Q'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 6}, page_content='PassengerId: 7\nSurvived: 0\nPclass: 1\nName: McCarthy, Mr. Timothy J\nSex: male\nAge: 54\nSibSp: 0\nParch: 0\nTicket: 17463\nFare: 51.8625\nCabin: E46\nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 7}, page_content='PassengerId: 8\nSurvived: 0\nPclass: 3\nName: Palsson, Master. Gosta Leonard\nSex: male\nAge: 2\nSibSp: 3\nParch: 1\nTicket: 349909\nFare: 21.075\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 8}, page_content='PassengerId: 9\nSurvived: 1\nPclass: 3\nName: Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)\nSex: female\nAge: 27\nSibSp: 0\nParch: 2\nTicket: 347742\nFare: 11.1333\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 9}, page_content='PassengerId: 10\nSurvived: 1\nPclass: 2\nName: Nasser, Mrs. Nicholas (Adele Achem)\nSex: female\nAge: 14\nSibSp: 1\nParch: 0\nTicket: 237736\nFare: 30.0708\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 10}, page_content='PassengerId: 11\nSurvived: 1\nPclass: 3\nName: Sandstrom, Miss. Marguerite Rut\nSex: female\nAge: 4\nSibSp: 1\nParch: 1\nTicket: PP 9549\nFare: 16.7\nCabin: G6\nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 11}, page_content='PassengerId: 12\nSurvived: 1\nPclass: 1\nName: Bonnell, Miss. Elizabeth\nSex: female\nAge: 58\nSibSp: 0\nParch: 0\nTicket: 113783\nFare: 26.55\nCabin: C103\nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 12}, page_content='PassengerId: 13\nSurvived: 0\nPclass: 3\nName: Saundercock, Mr. William Henry\nSex: male\nAge: 20\nSibSp: 0\nParch: 0\nTicket: A/5. 2151\nFare: 8.05\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 13}, page_content='PassengerId: 14\nSurvived: 0\nPclass: 3\nName: Andersson, Mr. Anders Johan\nSex: male\nAge: 39\nSibSp: 1\nParch: 5\nTicket: 347082\nFare: 31.275\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 14}, page_content='PassengerId: 15\nSurvived: 0\nPclass: 3\nName: Vestrom, Miss. Hulda Amanda Adolfina\nSex: female\nAge: 14\nSibSp: 0\nParch: 0\nTicket: 350406\nFare: 7.8542\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 15}, page_content='PassengerId: 16\nSurvived: 1\nPclass: 2\nName: Hewlett, Mrs. (Mary D Kingcome)\nSex: female\nAge: 55\nSibSp: 0\nParch: 0\nTicket: 248706\nFare: 16\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 16}, page_content='PassengerId: 17\nSurvived: 0\nPclass: 3\nName: Rice, Master. Eugene\nSex: male\nAge: 2\nSibSp: 4\nParch: 1\nTicket: 382652\nFare: 29.125\nCabin: \nEmbarked: Q'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 17}, page_content='PassengerId: 18\nSurvived: 1\nPclass: 2\nName: Williams, Mr. Charles Eugene\nSex: male\nAge: \nSibSp: 0\nParch: 0\nTicket: 244373\nFare: 13\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 18}, page_content='PassengerId: 19\nSurvived: 0\nPclass: 3\nName: Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)\nSex: female\nAge: 31\nSibSp: 1\nParch: 0\nTicket: 345763\nFare: 18\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 19}, page_content='PassengerId: 20\nSurvived: 1\nPclass: 3\nName: Masselmani, Mrs. Fatima\nSex: female\nAge: \nSibSp: 0\nParch: 0\nTicket: 2649\nFare: 7.225\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 20}, page_content='PassengerId: 21\nSurvived: 0\nPclass: 2\nName: Fynney, Mr. Joseph J\nSex: male\nAge: 35\nSibSp: 0\nParch: 0\nTicket: 239865\nFare: 26\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 21}, page_content='PassengerId: 22\nSurvived: 1\nPclass: 2\nName: Beesley, Mr. Lawrence\nSex: male\nAge: 34\nSibSp: 0\nParch: 0\nTicket: 248698\nFare: 13\nCabin: D56\nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 22}, page_content='PassengerId: 23\nSurvived: 1\nPclass: 3\nName: McGowan, Miss. Anna "Annie"\nSex: female\nAge: 15\nSibSp: 0\nParch: 0\nTicket: 330923\nFare: 8.0292\nCabin: \nEmbarked: Q'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 23}, page_content='PassengerId: 24\nSurvived: 1\nPclass: 1\nName: Sloper, Mr. William Thompson\nSex: male\nAge: 28\nSibSp: 0\nParch: 0\nTicket: 113788\nFare: 35.5\nCabin: A6\nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 24}, page_content='PassengerId: 25\nSurvived: 0\nPclass: 3\nName: Palsson, Miss. Torborg Danira\nSex: female\nAge: 8\nSibSp: 3\nParch: 1\nTicket: 349909\nFare: 21.075\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 25}, page_content='PassengerId: 26\nSurvived: 1\nPclass: 3\nName: Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)\nSex: female\nAge: 38\nSibSp: 1\nParch: 5\nTicket: 347077\nFare: 31.3875\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 26}, page_content='PassengerId: 27\nSurvived: 0\nPclass: 3\nName: Emir, Mr. Farred Chehab\nSex: male\nAge: \nSibSp: 0\nParch: 0\nTicket: 2631\nFare: 7.225\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 27}, page_content='PassengerId: 28\nSurvived: 0\nPclass: 1\nName: Fortune, Mr. Charles Alexander\nSex: male\nAge: 19\nSibSp: 3\nParch: 2\nTicket: 19950\nFare: 263\nCabin: C23 C25 C27\nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 28}, page_content='PassengerId: 29\nSurvived: 1\nPclass: 3\nName: O\'Dwyer, Miss. Ellen "Nellie"\nSex: female\nAge: \nSibSp: 0\nParch: 0\nTicket: 330959\nFare: 7.8792\nCabin: \nEmbarked: Q'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 29}, page_content='PassengerId: 30\nSurvived: 0\nPclass: 3\nName: Todoroff, Mr. Lalio\nSex: male\nAge: \nSibSp: 0\nParch: 0\nTicket: 349216\nFare: 7.8958\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 30}, page_content='PassengerId: 31\nSurvived: 0\nPclass: 1\nName: Uruchurtu, Don. Manuel E\nSex: male\nAge: 40\nSibSp: 0\nParch: 0\nTicket: PC 17601\nFare: 27.7208\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 31}, page_content='PassengerId: 32\nSurvived: 1\nPclass: 1\nName: Spencer, Mrs. William Augustus (Marie Eugenie)\nSex: female\nAge: \nSibSp: 1\nParch: 0\nTicket: PC 17569\nFare: 146.5208\nCabin: B78\nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 32}, page_content='PassengerId: 33\nSurvived: 1\nPclass: 3\nName: Glynn, Miss. Mary Agatha\nSex: female\nAge: \nSibSp: 0\nParch: 0\nTicket: 335677\nFare: 7.75\nCabin: \nEmbarked: Q'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 33}, page_content='PassengerId: 34\nSurvived: 0\nPclass: 2\nName: Wheadon, Mr. Edward H\nSex: male\nAge: 66\nSibSp: 0\nParch: 0\nTicket: C.A. 24579\nFare: 10.5\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 34}, page_content='PassengerId: 35\nSurvived: 0\nPclass: 1\nName: Meyer, Mr. Edgar Joseph\nSex: male\nAge: 28\nSibSp: 1\nParch: 0\nTicket: PC 17604\nFare: 82.1708\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 35}, page_content='PassengerId: 36\nSurvived: 0\nPclass: 1\nName: Holverson, Mr. Alexander Oskar\nSex: male\nAge: 42\nSibSp: 1\nParch: 0\nTicket: 113789\nFare: 52\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 36}, page_content='PassengerId: 37\nSurvived: 1\nPclass: 3\nName: Mamee, Mr. Hanna\nSex: male\nAge: \nSibSp: 0\nParch: 0\nTicket: 2677\nFare: 7.2292\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 37}, page_content='PassengerId: 38\nSurvived: 0\nPclass: 3\nName: Cann, Mr. Ernest Charles\nSex: male\nAge: 21\nSibSp: 0\nParch: 0\nTicket: A./5. 2152\nFare: 8.05\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 38}, page_content='PassengerId: 39\nSurvived: 0\nPclass: 3\nName: Vander Planke, Miss. Augusta Maria\nSex: female\nAge: 18\nSibSp: 2\nParch: 0\nTicket: 345764\nFare: 18\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 39}, page_content='PassengerId: 40\nSurvived: 1\nPclass: 3\nName: Nicola-Yarred, Miss. Jamila\nSex: female\nAge: 14\nSibSp: 1\nParch: 0\nTicket: 2651\nFare: 11.2417\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 40}, page_content='PassengerId: 41\nSurvived: 0\nPclass: 3\nName: Ahlin, Mrs. Johan (Johanna Persdotter Larsson)\nSex: female\nAge: 40\nSibSp: 1\nParch: 0\nTicket: 7546\nFare: 9.475\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 41}, page_content='PassengerId: 42\nSurvived: 0\nPclass: 2\nName: Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)\nSex: female\nAge: 27\nSibSp: 1\nParch: 0\nTicket: 11668\nFare: 21\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 42}, page_content='PassengerId: 43\nSurvived: 0\nPclass: 3\nName: Kraeff, Mr. Theodor\nSex: male\nAge: \nSibSp: 0\nParch: 0\nTicket: 349253\nFare: 7.8958\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 43}, page_content='PassengerId: 44\nSurvived: 1\nPclass: 2\nName: Laroche, Miss. Simonne Marie Anne Andree\nSex: female\nAge: 3\nSibSp: 1\nParch: 2\nTicket: SC/Paris 2123\nFare: 41.5792\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 44}, page_content='PassengerId: 45\nSurvived: 1\nPclass: 3\nName: Devaney, Miss. Margaret Delia\nSex: female\nAge: 19\nSibSp: 0\nParch: 0\nTicket: 330958\nFare: 7.8792\nCabin: \nEmbarked: Q'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 45}, page_content='PassengerId: 46\nSurvived: 0\nPclass: 3\nName: Rogers, Mr. William John\nSex: male\nAge: \nSibSp: 0\nParch: 0\nTicket: S.C./A.4. 23567\nFare: 8.05\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 46}, page_content='PassengerId: 47\nSurvived: 0\nPclass: 3\nName: Lennon, Mr. Denis\nSex: male\nAge: \nSibSp: 1\nParch: 0\nTicket: 370371\nFare: 15.5\nCabin: \nEmbarked: Q'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 47}, page_content="PassengerId: 48\nSurvived: 1\nPclass: 3\nName: O'Driscoll, Miss. Bridget\nSex: female\nAge: \nSibSp: 0\nParch: 0\nTicket: 14311\nFare: 7.75\nCabin: \nEmbarked: Q"),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 48}, page_content='PassengerId: 49\nSurvived: 0\nPclass: 3\nName: Samaan, Mr. Youssef\nSex: male\nAge: \nSibSp: 2\nParch: 0\nTicket: 2662\nFare: 21.6792\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 49}, page_content='PassengerId: 50\nSurvived: 0\nPclass: 3\nName: Arnold-Franchi, Mrs. Josef (Josefine Franchi)\nSex: female\nAge: 18\nSibSp: 1\nParch: 0\nTicket: 349237\nFare: 17.8\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 50}, page_content='PassengerId: 51\nSurvived: 0\nPclass: 3\nName: Panula, Master. Juha Niilo\nSex: male\nAge: 7\nSibSp: 4\nParch: 1\nTicket: 3101295\nFare: 39.6875\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 51}, page_content='PassengerId: 52\nSurvived: 0\nPclass: 3\nName: Nosworthy, Mr. Richard Cater\nSex: male\nAge: 21\nSibSp: 0\nParch: 0\nTicket: A/4. 39886\nFare: 7.8\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 52}, page_content='PassengerId: 53\nSurvived: 1\nPclass: 1\nName: Harper, Mrs. Henry Sleeper (Myna Haxtun)\nSex: female\nAge: 49\nSibSp: 1\nParch: 0\nTicket: PC 17572\nFare: 76.7292\nCabin: D33\nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 53}, page_content='PassengerId: 54\nSurvived: 1\nPclass: 2\nName: Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)\nSex: female\nAge: 29\nSibSp: 1\nParch: 0\nTicket: 2926\nFare: 26\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 54}, page_content='PassengerId: 55\nSurvived: 0\nPclass: 1\nName: Ostby, Mr. Engelhart Cornelius\nSex: male\nAge: 65\nSibSp: 0\nParch: 1\nTicket: 113509\nFare: 61.9792\nCabin: B30\nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 55}, page_content='PassengerId: 56\nSurvived: 1\nPclass: 1\nName: Woolner, Mr. Hugh\nSex: male\nAge: \nSibSp: 0\nParch: 0\nTicket: 19947\nFare: 35.5\nCabin: C52\nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 56}, page_content='PassengerId: 57\nSurvived: 1\nPclass: 2\nName: Rugg, Miss. Emily\nSex: female\nAge: 21\nSibSp: 0\nParch: 0\nTicket: C.A. 31026\nFare: 10.5\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 57}, page_content='PassengerId: 58\nSurvived: 0\nPclass: 3\nName: Novel, Mr. Mansouer\nSex: male\nAge: 28.5\nSibSp: 0\nParch: 0\nTicket: 2697\nFare: 7.2292\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 58}, page_content='PassengerId: 59\nSurvived: 1\nPclass: 2\nName: West, Miss. Constance Mirium\nSex: female\nAge: 5\nSibSp: 1\nParch: 2\nTicket: C.A. 34651\nFare: 27.75\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 59}, page_content='PassengerId: 60\nSurvived: 0\nPclass: 3\nName: Goodwin, Master. William Frederick\nSex: male\nAge: 11\nSibSp: 5\nParch: 2\nTicket: CA 2144\nFare: 46.9\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 60}, page_content='PassengerId: 61\nSurvived: 0\nPclass: 3\nName: Sirayanian, Mr. Orsen\nSex: male\nAge: 22\nSibSp: 0\nParch: 0\nTicket: 2669\nFare: 7.2292\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 61}, page_content='PassengerId: 62\nSurvived: 1\nPclass: 1\nName: Icard, Miss. Amelie\nSex: female\nAge: 38\nSibSp: 0\nParch: 0\nTicket: 113572\nFare: 80\nCabin: B28\nEmbarked: '),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 62}, page_content='PassengerId: 63\nSurvived: 0\nPclass: 1\nName: Harris, Mr. Henry Birkhardt\nSex: male\nAge: 45\nSibSp: 1\nParch: 0\nTicket: 36973\nFare: 83.475\nCabin: C83\nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 63}, page_content='PassengerId: 64\nSurvived: 0\nPclass: 3\nName: Skoog, Master. Harald\nSex: male\nAge: 4\nSibSp: 3\nParch: 2\nTicket: 347088\nFare: 27.9\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 64}, page_content='PassengerId: 65\nSurvived: 0\nPclass: 1\nName: Stewart, Mr. Albert A\nSex: male\nAge: \nSibSp: 0\nParch: 0\nTicket: PC 17605\nFare: 27.7208\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 65}, page_content='PassengerId: 66\nSurvived: 1\nPclass: 3\nName: Moubarek, Master. Gerios\nSex: male\nAge: \nSibSp: 1\nParch: 1\nTicket: 2661\nFare: 15.2458\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 66}, page_content='PassengerId: 67\nSurvived: 1\nPclass: 2\nName: Nye, Mrs. (Elizabeth Ramell)\nSex: female\nAge: 29\nSibSp: 0\nParch: 0\nTicket: C.A. 29395\nFare: 10.5\nCabin: F33\nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 67}, page_content='PassengerId: 68\nSurvived: 0\nPclass: 3\nName: Crease, Mr. Ernest James\nSex: male\nAge: 19\nSibSp: 0\nParch: 0\nTicket: S.P. 3464\nFare: 8.1583\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 68}, page_content='PassengerId: 69\nSurvived: 1\nPclass: 3\nName: Andersson, Miss. Erna Alexandra\nSex: female\nAge: 17\nSibSp: 4\nParch: 2\nTicket: 3101281\nFare: 7.925\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 69}, page_content='PassengerId: 70\nSurvived: 0\nPclass: 3\nName: Kink, Mr. Vincenz\nSex: male\nAge: 26\nSibSp: 2\nParch: 0\nTicket: 315151\nFare: 8.6625\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 70}, page_content='PassengerId: 71\nSurvived: 0\nPclass: 2\nName: Jenkin, Mr. Stephen Curnow\nSex: male\nAge: 32\nSibSp: 0\nParch: 0\nTicket: C.A. 33111\nFare: 10.5\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 71}, page_content='PassengerId: 72\nSurvived: 0\nPclass: 3\nName: Goodwin, Miss. Lillian Amy\nSex: female\nAge: 16\nSibSp: 5\nParch: 2\nTicket: CA 2144\nFare: 46.9\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 72}, page_content='PassengerId: 73\nSurvived: 0\nPclass: 2\nName: Hood, Mr. Ambrose Jr\nSex: male\nAge: 21\nSibSp: 0\nParch: 0\nTicket: S.O.C. 14879\nFare: 73.5\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 73}, page_content='PassengerId: 74\nSurvived: 0\nPclass: 3\nName: Chronopoulos, Mr. Apostolos\nSex: male\nAge: 26\nSibSp: 1\nParch: 0\nTicket: 2680\nFare: 14.4542\nCabin: \nEmbarked: C'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 74}, page_content='PassengerId: 75\nSurvived: 1\nPclass: 3\nName: Bing, Mr. Lee\nSex: male\nAge: 32\nSibSp: 0\nParch: 0\nTicket: 1601\nFare: 56.4958\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 75}, page_content='PassengerId: 76\nSurvived: 0\nPclass: 3\nName: Moen, Mr. Sigurd Hansen\nSex: male\nAge: 25\nSibSp: 0\nParch: 0\nTicket: 348123\nFare: 7.65\nCabin: F G73\nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 76}, page_content='PassengerId: 77\nSurvived: 0\nPclass: 3\nName: Staneff, Mr. Ivan\nSex: male\nAge: \nSibSp: 0\nParch: 0\nTicket: 349208\nFare: 7.8958\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 77}, page_content='PassengerId: 78\nSurvived: 0\nPclass: 3\nName: Moutal, Mr. Rahamin Haim\nSex: male\nAge: \nSibSp: 0\nParch: 0\nTicket: 374746\nFare: 8.05\nCabin: \nEmbarked: S'),
 Document(metadata={'source': 'Titanic-Dataset.csv', 'row': 78}, page_content='PassengerId: 79\nSurvived: 1\nPclass: 2\nName: Caldwell, Master. Alden Gates\nSex: male\nAge: 0.83\nSibSp: 0\nParch: 2\nTicket: 248738\nFare: 29\nCabin: \nEmbarked: S'),

In [11]:
data[0].metadata

{'source': 'nvda_news_1.txt'}

In [15]:
from langchain.document_loaders import UnstructuredURLLoader

In [16]:
loader = UnstructuredURLLoader(urls=["https://www.moneycontrol.com/news/business/banks/hdfc-bank-re-appoints-sanmoy-chakrabarti-as-chief-risk-officer-11259771.html","https://www.moneycontrol.com/news/business/markets/stock-market-news-live-updates-november-1-2023-11259771.html"])

In [17]:
data = loader.load()

In [18]:
data[0].metadata

{'source': 'https://www.moneycontrol.com/news/business/banks/hdfc-bank-re-appoints-sanmoy-chakrabarti-as-chief-risk-officer-11259771.html'}

In [ ]:
# text splitting